"""
Key Generation — "Vinyl Record" Simulator
==========================================
In the real SIGSALY, the encryption key was a vinyl phonograph record filled
with random noise. This module simulates the generation, storage, duplication,
and distribution of these key records.

Historical context:
  The random values on SIGSALY's key records were generated by large
  mercury-vapor rectifying vacuum tubes — essentially using thermal noise
  from hot ionized mercury as a source of true randomness. This was
  state-of-the-art random number generation for the 1940s.

  The manufacturing process:
    1. Generate random noise using mercury-vapor tubes
    2. Sample the noise 50 times/sec across 12 channels (10 bands + pitch + voiced)
    3. Quantize each sample to 6 levels (0-5)
    4. Record the values onto a vinyl phonograph record
    5. Press an IDENTICAL copy of the record
    6. Ship one copy to each terminal by armed courier

  Key logistics:
    - Each record held 12 minutes of key material
    - A conversation required one record per direction (2 records per call)
    - Each terminal had TWO turntables for seamless crossover
    - Used records were IMMEDIATELY DESTROYED (ensuring "one-time" property)
    - Records were shipped by armed military courier — a physical key
      distribution channel that predates modern key exchange protocols

  The physical key distribution problem:
    SIGSALY's security ultimately depended on the physical security of the
    vinyl records during transit. If an enemy intercepted and copied a
    record, they could decrypt the corresponding conversation. This is the
    same fundamental challenge faced by modern key management systems —
    the encryption algorithm can be perfect, but security depends on
    keeping the keys secret.

Key structure:
  A key record contains random values matching the vocoder output format:
    - band_key:  (n_frames, 10) array of random integers in [0, 5]
    - pitch_key: (n_frames,) array of random integers in [0, 35]
    - metadata:  generation parameters for reproducibility

  At 50 frames/sec, a 12-minute record contains:
    12 × 60 × 50 = 36,000 frames
    36,000 × (10 + 1) = 396,000 random values

  This is the "key material" — enough randomness for 12 minutes of
  perfectly encrypted conversation.
"""

import numpy as np
import json
import os
from .vocoder import NUM_BANDS, NUM_LEVELS, FRAME_RATE


def generate_key_record(duration_seconds, seed=None, verbose=False):
    """Generate a random key record (simulated vinyl record).

    This simulates the mercury-vapor tube noise generation and recording
    process. In our simulator, we use a pseudorandom number generator
    (numpy's PCG64) instead of actual hardware noise. For educational
    purposes, an optional seed provides reproducibility.

    Note: In real SIGSALY, a deterministic seed would be a FATAL flaw —
    the key must be truly random (unpredictable). We use seeds here only
    for reproducible demonstrations.

    Args:
        duration_seconds: Length of key material in seconds.
                          Real SIGSALY records held 12 minutes (720 seconds).
        seed:             Random seed for reproducibility (None = truly random).
                          WARNING: seeds make the key predictable!
        verbose:          Print diagnostic information

    Returns:
        dict with:
          - band_key:  (n_frames, 10) random int array, values in [0, 5]
          - pitch_key: (n_frames,) random int array, values in [0, 35]
          - metadata:  dict with generation parameters
    """
    rng = np.random.default_rng(seed)
    n_frames = int(duration_seconds * FRAME_RATE)

    # Generate random key values for each vocoder channel.
    # Every value is independently, uniformly random — this is what
    # gives the one-time pad its perfect secrecy.
    key = {
        # 10 band amplitude keys: each independently random in [0, 5]
        'band_key': rng.integers(0, NUM_LEVELS, size=(n_frames, NUM_BANDS)),
        # Pitch key: random in [0, 35] (matching the 36-level pitch quantization)
        'pitch_key': rng.integers(0, 36, size=n_frames),
        'metadata': {
            'duration_seconds': duration_seconds,
            'n_frames': n_frames,
            'frame_rate': FRAME_RATE,
            'num_bands': NUM_BANDS,
            'num_levels': NUM_LEVELS,
            'seed': seed,
        }
    }

    if verbose:
        _print_key_diagnostics(key)

    return key


def save_key_record(key, filepath):
    """Save a key record to disk.

    In the SIGSALY analogy, this is "pressing the vinyl record" — committing
    the random values to a physical medium that can be transported.

    We use numpy's .npz format (compressed numpy arrays) — efficient for
    storing large integer arrays.

    Args:
        key:      Key record dict from generate_key_record
        filepath: Output file path (typically .npz extension)

    Returns:
        The filepath (for convenience)
    """
    np.savez(filepath,
             band_key=key['band_key'],
             pitch_key=key['pitch_key'],
             metadata=json.dumps(key['metadata']))
    return filepath


def load_key_record(filepath):
    """Load a key record from disk.

    In the SIGSALY analogy, this is "placing the record on the turntable"
    — loading the key material so it's ready for encryption or decryption.
    """
    data = np.load(filepath, allow_pickle=False)
    key = {
        'band_key': data['band_key'],
        'pitch_key': data['pitch_key'],
        'metadata': json.loads(str(data['metadata'])),
    }
    return key


def duplicate_key_record(key):
    """Create an identical copy of a key record.

    In the real SIGSALY, this happened at the manufacturing facility.
    Both copies had to be absolutely identical — any difference between
    the sender's and receiver's key would cause decryption errors.

    The duplication process was a critical security concern: the fewer
    copies that exist, the smaller the attack surface. SIGSALY made
    exactly two copies of each record — one for each terminal.

    Returns:
        A new dict with copied arrays (modifying one won't affect the other)
    """
    return {
        'band_key': key['band_key'].copy(),
        'pitch_key': key['pitch_key'].copy(),
        'metadata': dict(key['metadata']),
    }


def _print_key_diagnostics(key):
    """Print quantitative diagnostics about the generated key."""
    band_key = key['band_key']
    pitch_key = key['pitch_key']
    n_frames = len(band_key)
    n_band_values = band_key.size

    print()
    print("  ┌─ Key Record Diagnostics ─────────────────────────────")
    print(f"  │ Duration: {key['metadata']['duration_seconds']:.1f}s ({n_frames} frames at {FRAME_RATE} fps)")
    print(f"  │ Total key values: {n_band_values + len(pitch_key):,}")
    print(f"  │   Band keys:  {n_band_values:,} ({n_frames} frames × {NUM_BANDS} bands)")
    print(f"  │   Pitch keys: {len(pitch_key):,}")

    if key['metadata']['seed'] is not None:
        print(f"  │")
        print(f"  │ ⚠ SEEDED (seed={key['metadata']['seed']}) — predictable/reproducible!")
        print(f"  │   Real SIGSALY used TRUE random noise (mercury-vapor tubes).")

    # Verify randomness: check distribution uniformity
    print(f"  │")
    print(f"  │ Band key value distribution (should be uniform 0-5):")
    for lv in range(NUM_LEVELS):
        count = np.sum(band_key == lv)
        pct = 100 * count / n_band_values
        expected = 100 / NUM_LEVELS
        bar = '█' * int(pct / 2)
        print(f"  │   Level {lv}: {pct:5.1f}% (expected {expected:.1f}%) {bar}")

    # Check for sequential correlation (adjacent values should be independent)
    flat = band_key.flatten().astype(float)
    if len(flat) > 1:
        autocorr = np.corrcoef(flat[:-1], flat[1:])[0, 1]
        print(f"  │")
        print(f"  │ Sequential correlation: {autocorr:.4f} (should be ~0.0)")
        if abs(autocorr) < 0.05:
            print(f"  │ → GOOD: No detectable pattern between adjacent values")
        else:
            print(f"  │ → Note: Some correlation detected (OK for demo, not for real use)")

    # Physical analogy
    print(f"  │")
    vinyl_minutes = key['metadata']['duration_seconds'] / 60
    print(f"  │ Physical analogy:")
    print(f"  │   This key record would fill {vinyl_minutes:.1f} min of vinyl")
    print(f"  │   (Real SIGSALY records held 12 min each)")
    print(f"  │   Each terminal needed 2 turntables for uninterrupted operation")
    if vinyl_minutes > 12:
        n_records = int(np.ceil(vinyl_minutes / 12))
        print(f"  │   This conversation would require {n_records} record(s) per side")
    print(f"  └──────────────────────────────────────────────────────")
    print()


if __name__ == '__main__':
    import sys

    duration = float(sys.argv[1]) if len(sys.argv) > 1 else 30
    seed = int(sys.argv[2]) if len(sys.argv) > 2 else None
    outpath = sys.argv[3] if len(sys.argv) > 3 else 'output/key_record.npz'

    print(f"Key Record Generator ('Vinyl Record' Simulator)")
    print(f"=" * 50)

    key = generate_key_record(duration, seed=seed, verbose=True)

    os.makedirs(os.path.dirname(outpath) or '.', exist_ok=True)
    save_key_record(key, outpath)
    print(f"  Key record saved: {outpath}")
    print(f"  File size: {os.path.getsize(outpath + '.npz' if not outpath.endswith('.npz') else outpath):,} bytes")
