"""
Key Generation — "Vinyl Record" Simulator
==========================================
In the real SIGSALY, the encryption key was a vinyl phonograph record filled
with random noise. This module simulates the generation, storage, duplication,
and distribution of these key records.

Historical context:
  The random values on SIGSALY's key records were generated by large
  mercury-vapor rectifying vacuum tubes — essentially using thermal noise
  from hot ionized mercury as a source of true randomness. This was
  state-of-the-art random number generation for the 1940s.

  The manufacturing process:
    1. Generate random noise using mercury-vapor tubes
    2. Sample the noise 50 times/sec across the vocoder channels
    3. Quantize each sample to 6 levels (0-5)
    4. Record the values onto a vinyl phonograph record
    5. Press an IDENTICAL copy of the record
    6. Ship one copy to each terminal by armed courier

  Key logistics:
    - Each record held 12 minutes of key material
    - A conversation required one record per direction (2 records per call)
    - Each terminal had TWO turntables for seamless crossover
    - Used records were IMMEDIATELY DESTROYED (ensuring "one-time" property)
    - Records were shipped by armed military courier — a physical key
      distribution channel that predates modern key exchange protocols

  The physical key distribution problem:
    SIGSALY's security ultimately depended on the physical security of the
    vinyl records during transit. If an enemy intercepted and copied a
    record, they could decrypt the corresponding conversation. This is the
    same fundamental challenge faced by modern key management systems —
    the encryption algorithm can be perfect, but security depends on
    keeping the keys secret.

Key structure:
  A key record contains random values matching the vocoder output format:
    - band_key:  (n_frames, 10) array of random integers in [0, 5]
    - pitch_key: (n_frames,) array of random integers in [0, 35]
    - metadata:  generation parameters for reproducibility

  At 50 frames/sec, a 12-minute record contains:
    12 × 60 × 50 = 36,000 frames
    36,000 × (10 + 1) = 396,000 random values

  This is the "key material" — enough randomness for 12 minutes of
  perfectly encrypted conversation.
"""

import numpy as np
import json
import os
from .vocoder import NUM_BANDS, NUM_LEVELS, FRAME_RATE


def generate_key_record(duration_seconds, seed=None, verbose=False):
    """Generate a random key record (simulated vinyl record).

    This simulates the mercury-vapor tube noise generation and recording
    process. In our simulator, we use a pseudorandom number generator
    (numpy's PCG64) instead of actual hardware noise. For educational
    purposes, an optional seed provides reproducibility.

    Note: In real SIGSALY, a deterministic seed would be a FATAL flaw —
    the key must be truly random (unpredictable). We use seeds here only
    for reproducible demonstrations.

    Args:
        duration_seconds: Length of key material in seconds.
                          Real SIGSALY records held 12 minutes (720 seconds).
        seed:             Random seed for reproducibility (None = truly random).
                          WARNING: seeds make the key predictable!
        verbose:          Print diagnostic information

    Returns:
        dict with:
          - band_key:  (n_frames, 10) random int array, values in [0, 5]
          - pitch_key: (n_frames,) random int array, values in [0, 35]
          - metadata:  dict with generation parameters
    """
    rng = np.random.default_rng(seed)
    n_frames = int(duration_seconds * FRAME_RATE)

    # Generate random key values for each vocoder channel.
    # Every value is independently, uniformly random — this is what
    # gives the one-time pad its perfect secrecy.
    key = {
        # 10 band amplitude keys: each independently random in [0, 5]
        'band_key': rng.integers(0, NUM_LEVELS, size=(n_frames, NUM_BANDS)),
        # Pitch key: random in [0, 35] (matching the 36-level pitch quantization)
        'pitch_key': rng.integers(0, 36, size=n_frames),
        'metadata': {
            'duration_seconds': duration_seconds,
            'n_frames': n_frames,
            'frame_rate': FRAME_RATE,
            'num_bands': NUM_BANDS,
            'num_levels': NUM_LEVELS,
            'seed': seed,
        }
    }

    if verbose:
        _print_key_diagnostics(key)

    return key


def save_key_record(key, filepath):
    """Save a key record to disk.

    In the SIGSALY analogy, this is "pressing the vinyl record" — committing
    the random values to a physical medium that can be transported.

    We use numpy's .npz format (compressed numpy arrays) — efficient for
    storing large integer arrays.

    Args:
        key:      Key record dict from generate_key_record
        filepath: Output file path (typically .npz extension)

    Returns:
        The filepath (for convenience)
    """
    np.savez(filepath,
             band_key=key['band_key'],
             pitch_key=key['pitch_key'],
             metadata=json.dumps(key['metadata']))
    return filepath


def load_key_record(filepath):
    """Load a key record from disk.

    In the SIGSALY analogy, this is "placing the record on the turntable"
    — loading the key material so it's ready for encryption or decryption.
    """
    data = np.load(filepath, allow_pickle=False)
    key = {
        'band_key': data['band_key'],
        'pitch_key': data['pitch_key'],
        'metadata': json.loads(str(data['metadata'])),
    }
    return key


def duplicate_key_record(key):
    """Create an identical copy of a key record.

    In the real SIGSALY, this happened at the manufacturing facility.
    Both copies had to be absolutely identical — any difference between
    the sender's and receiver's key would cause decryption errors.

    The duplication process was a critical security concern: the fewer
    copies that exist, the smaller the attack surface. SIGSALY made
    exactly two copies of each record — one for each terminal.

    Returns:
        A new dict with copied arrays (modifying one won't affect the other)
    """
    return {
        'band_key': key['band_key'].copy(),
        'pitch_key': key['pitch_key'].copy(),
        'metadata': dict(key['metadata']),
    }


def key_to_audio(key, sr=22050):
    """Convert a key record to audible audio — what the vinyl sounded like.

    In the real SIGSALY, the key records were vinyl phonograph records filled
    with random noise from mercury-vapor vacuum tubes. If you played one on
    a regular phonograph, you'd hear noise — because that's literally what
    was recorded on them.

    This function renders the key as audio in two combined layers:

    1. Raw noise band: white noise filtered to telephone bandwidth (300-3400 Hz).
       This is what the physical vinyl record sounded like — the analog noise
       from the mercury-vapor tubes before quantization.

    2. Vocoder-resynthesized key: the quantized key values (0-5) fed through
       the vocoder synthesizer. This sounds like random robotic babble —
       it's what the key "means" as vocoder parameters. Since the values
       are random, you get random band amplitudes and random pitch, producing
       no speech-like structure at all.

    Listening to this helps students understand:
      - The key is just NOISE — there's no hidden message in it
      - When this noise is subtracted from speech (mod 6), it obliterates
        all speech structure in the encrypted output
      - The vinyl record was literally a physical random number generator

    Args:
        key: Key record dict from generate_key_record
        sr:  Sample rate for the output audio

    Returns:
        Audio signal (1D numpy array) at the given sample rate
    """
    from .vocoder import array_to_frames, synthesize

    n_frames = len(key['band_key'])

    # Layer 1: Raw noise (what the physical vinyl sounded like)
    # Generate white noise, bandpass to telephone range
    n_samples = n_frames * (sr // FRAME_RATE)
    raw_noise = np.random.normal(0, 0.3, n_samples)
    from scipy.signal import butter, sosfilt
    sos = butter(4, [300, 3400], btype='band', fs=sr, output='sos')
    raw_noise = sosfilt(sos, raw_noise)

    # Layer 2: Vocoder resynthesis of the random key values
    # Feed the random 0-5 values through the vocoder to hear what
    # "random vocoder parameters" sound like (random robotic babble)
    voiced_random = np.random.choice([True, False], size=n_frames, p=[0.5, 0.5])
    max_vals = np.ones(n_frames)
    frames = array_to_frames(key['band_key'], key['pitch_key'], voiced_random, max_vals)
    vocoder_noise = synthesize(frames, sr)

    # Mix: mostly raw noise with vocoder texture underneath
    min_len = min(len(raw_noise), len(vocoder_noise))
    mixed = 0.6 * raw_noise[:min_len] + 0.4 * vocoder_noise[:min_len]

    # Normalize
    peak = np.max(np.abs(mixed))
    if peak > 0:
        mixed = mixed / peak * 0.95

    return mixed


def _print_key_diagnostics(key):
    """Print quantitative diagnostics about the generated key."""
    band_key = key['band_key']
    pitch_key = key['pitch_key']
    n_frames = len(band_key)
    n_band_values = band_key.size

    print()
    print("  ┌─ Key Record Diagnostics ─────────────────────────────")
    print(f"  │ Duration: {key['metadata']['duration_seconds']:.1f}s ({n_frames} frames at {FRAME_RATE} fps)")
    print(f"  │ Total key values: {n_band_values + len(pitch_key):,}")
    print(f"  │   Band keys:  {n_band_values:,} ({n_frames} frames × {NUM_BANDS} bands)")
    print(f"  │   Pitch keys: {len(pitch_key):,}")

    if key['metadata']['seed'] is not None:
        print(f"  │")
        print(f"  │ ⚠ SEEDED (seed={key['metadata']['seed']}) — predictable/reproducible!")
        print(f"  │   Real SIGSALY used TRUE random noise (mercury-vapor tubes).")

    # Verify randomness: check distribution uniformity
    print(f"  │")
    print(f"  │ Band key value distribution (should be uniform 0-5):")
    for lv in range(NUM_LEVELS):
        count = np.sum(band_key == lv)
        pct = 100 * count / n_band_values
        expected = 100 / NUM_LEVELS
        bar = '█' * int(pct / 2)
        print(f"  │   Level {lv}: {pct:5.1f}% (expected {expected:.1f}%) {bar}")

    # Check for sequential correlation (adjacent values should be independent)
    flat = band_key.flatten().astype(float)
    if len(flat) > 1:
        autocorr = np.corrcoef(flat[:-1], flat[1:])[0, 1]
        print(f"  │")
        print(f"  │ Sequential correlation: {autocorr:.4f} (should be ~0.0)")
        if abs(autocorr) < 0.05:
            print(f"  │ → GOOD: No detectable pattern between adjacent values")
        else:
            print(f"  │ → Note: Some correlation detected (OK for demo, not for real use)")

    # Physical analogy
    print(f"  │")
    vinyl_minutes = key['metadata']['duration_seconds'] / 60
    print(f"  │ Physical analogy:")
    print(f"  │   This key record would fill {vinyl_minutes:.1f} min of vinyl")
    print(f"  │   (Real SIGSALY records held 12 min each)")
    print(f"  │   Each terminal needed 2 turntables for uninterrupted operation")
    if vinyl_minutes > 12:
        n_records = int(np.ceil(vinyl_minutes / 12))
        print(f"  │   This conversation would require {n_records} record(s) per side")
    print(f"  └──────────────────────────────────────────────────────")
    print()


if __name__ == '__main__':
    import sys
    import soundfile as sf

    if len(sys.argv) < 2:
        print("Usage: python -m sigsaly.key_generation <duration_seconds> [seed] [output_dir]")
        print()
        print("Generates a random key record ('vinyl record') and exports it as both")
        print("a .npz data file and a .wav audio file so you can HEAR the key.")
        print()
        print("Args:")
        print("  duration_seconds  Length of key material in seconds")
        print("  seed              Random seed for reproducibility (optional)")
        print("  output_dir        Output directory (default: output/)")
        print()
        print("Examples:")
        print("  python -m sigsaly.key_generation 30              # 30s of key material")
        print("  python -m sigsaly.key_generation 10 42           # reproducible with seed")
        print("  python -m sigsaly.key_generation 60 None results/  # 60s, random, custom dir")
        print()
        print("Outputs:")
        print("  key_record.npz  — Key data (for encryption/decryption)")
        print("  key_record.wav  — Audible key (what the vinyl record sounded like)")
        sys.exit(1)

    duration = float(sys.argv[1])
    seed = int(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[2] != 'None' else None
    outdir = sys.argv[3] if len(sys.argv) > 3 else 'output'

    print(f"Key Record Generator ('Vinyl Record' Simulator)")
    print(f"=" * 55)

    key = generate_key_record(duration, seed=seed, verbose=True)

    os.makedirs(outdir, exist_ok=True)

    # Save the data file
    npz_path = os.path.join(outdir, 'key_record.npz')
    save_key_record(key, npz_path)
    print(f"  Key data saved: {npz_path}")

    # Render and save the audio version
    print(f"\n  Rendering key as audio (what the vinyl record sounded like)...")
    sr = 22050
    audio = key_to_audio(key, sr=sr)
    wav_path = os.path.join(outdir, 'key_record.wav')
    sf.write(wav_path, audio, sr)
    print(f"  Key audio saved: {wav_path} ({len(audio)/sr:.2f}s)")
    print()
    print(f"  🎵 Listen to {wav_path} — this is what an eavesdropper would hear")
    print(f"     if they played the vinyl key record on a phonograph: random noise.")
    print(f"     There's no speech in it, no pattern — just the raw randomness")
    print(f"     that makes the one-time pad unbreakable.")
