"""
SIGSALY Simulator — Flask Web Dashboard (v2)
=============================================
A simple web interface for the SIGSALY educational pipeline.
Upload audio (or use the built-in sample), tweak parameters,
and hear/see all outputs with audio players and spectrograms.

Usage (single user / local development):
    python web/app.py                    # default port 3001
    python web/app.py --port 8080        # custom port

Usage (multi-user / classroom):
    ./serve.sh                           # 8 workers on port 3001
    ./serve.sh --workers 12 --port 8080  # custom

Pre-computing defaults (run once):
    python scripts/precompute_default.py
"""

import os
import sys
import json
import argparse
import tempfile

# Add project root to path so sigsaly package is importable
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from flask import Flask, render_template, request, send_from_directory
import soundfile as sf

from web.pipeline import run_web_pipeline, cleanup_old_sessions
from web.pipeline_v3 import run_v3_pipeline, cleanup_v3_sessions

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16 MB upload limit

VALID_THEMES = {'default', 'codex'}
VALID_SOURCE_MODES = {'builtin', 'upload', 'record'}

# Maximum audio duration in seconds. Longer clips take proportionally longer
# to process (vocoder analysis, cracking search, spectrogram generation).
# 120s is generous for educational demos — most speech clips are 5-30s.
MAX_AUDIO_DURATION = 120

# Default sample audio path
DEFAULT_SAMPLE = os.path.join(PROJECT_ROOT, 'input', 'sample_speech_eleven.mp3')

# Pre-computed default output directory (generated by scripts/precompute_default.py)
DEFAULT_OUTPUT_DIR = os.path.join(PROJECT_ROOT, 'web', 'default_output')
DEFAULT_RESULTS_JSON = os.path.join(DEFAULT_OUTPUT_DIR, 'results.json')

# Special session_id used for pre-computed defaults
DEFAULT_SESSION_ID = '_default'

# v3 pre-computed defaults
V3_DEFAULT_DIR = os.path.join(PROJECT_ROOT, 'web', 'v3_default_output')
V3_DEFAULT_MANIFEST = os.path.join(V3_DEFAULT_DIR, 'manifest.json')
V3_DEFAULT_SESSION_ID = '_v3_default'


def _normalize_theme(theme):
    """Limit theme selection to the supported UI variants."""
    return theme if theme in VALID_THEMES else 'default'


def _normalize_source_mode(source_mode):
    """Limit source selection to the supported input modes."""
    return source_mode if source_mode in VALID_SOURCE_MODES else 'builtin'


def _get_default_source_info():
    """Return metadata for the built-in sample used by the root app."""
    default_info = sf.info(DEFAULT_SAMPLE)
    return {
        'name': 'Built-in sample',
        'duration': round(default_info.duration, 2),
        'sr': default_info.samplerate,
    }


def _render_index(*, theme, results=None, error=None, active_source_mode='builtin', is_default=False):
    """Render the root app with consistent shared context."""
    return render_template(
        'index.html',
        results=results,
        error=error,
        default_source=_get_default_source_info(),
        max_duration=MAX_AUDIO_DURATION,
        is_default=is_default,
        theme=theme,
        active_source_mode=_normalize_source_mode(active_source_mode),
    )


def _load_default_results():
    """Load pre-computed default results if available."""
    if not os.path.exists(DEFAULT_RESULTS_JSON):
        return None
    try:
        with open(DEFAULT_RESULTS_JSON, 'r') as f:
            results = json.load(f)
        # Use the special default session ID so routes know to serve
        # from default_output/ instead of a temp directory
        results['session_id'] = DEFAULT_SESSION_ID
        results['session_dir'] = DEFAULT_OUTPUT_DIR
        return results
    except Exception:
        return None


@app.route('/')
def index():
    """Render the main page with pre-computed default results if available."""
    theme = _normalize_theme(request.args.get('theme'))
    default_results = _load_default_results()

    if default_results:
        # Serve the page with pre-computed results — instant load
        return _render_index(
            theme=theme,
            results=default_results,
            is_default=True,
            active_source_mode='builtin',
        )
    else:
        # No pre-computed results — show empty form with preview player
        return _render_index(theme=theme, active_source_mode='builtin')


@app.route('/run', methods=['POST'])
def run_pipeline():
    """Accept audio input, run the SIGSALY pipeline, return results."""
    theme = _normalize_theme(request.form.get('theme') or request.args.get('theme'))
    source_mode = _normalize_source_mode(request.form.get('source_mode'))
    cleanup_old_sessions()

    # Determine input audio source
    input_path = None
    source_name = 'Built-in sample'
    is_custom_upload = False
    temp_input_path = None

    if source_mode in {'upload', 'record'}:
        uploaded = request.files.get('audio_file')
        if not uploaded or not uploaded.filename:
            error = ('Please choose a file to upload.' if source_mode == 'upload'
                     else 'Please record audio before running the pipeline.')
            return _render_index(
                theme=theme,
                error=error,
                active_source_mode=source_mode,
            )

        suffix = os.path.splitext(uploaded.filename)[1] or '.wav'
        with tempfile.NamedTemporaryFile(prefix='sigsaly_input_', suffix=suffix, delete=False) as tmp:
            temp_input_path = tmp.name
        uploaded.save(temp_input_path)

        # Validate it's a readable audio file
        try:
            info = sf.info(temp_input_path)
        except Exception as e:
            if temp_input_path and os.path.exists(temp_input_path):
                os.unlink(temp_input_path)
            return _render_index(
                theme=theme,
                error=f'Invalid audio file: {e}',
                active_source_mode=source_mode,
            )

        # Enforce duration limit
        if info.duration > MAX_AUDIO_DURATION:
            if temp_input_path and os.path.exists(temp_input_path):
                os.unlink(temp_input_path)
            return _render_index(
                theme=theme,
                error=(f'Audio too long: {info.duration:.1f}s '
                       f'(maximum {MAX_AUDIO_DURATION}s). '
                       f'Please trim your audio and try again.'),
                active_source_mode=source_mode,
            )

        input_path = temp_input_path
        source_name = 'Microphone recording' if source_mode == 'record' else uploaded.filename
        is_custom_upload = True
    else:
        # Using default sample — check if we need to re-run
        # (only re-run if params differ from the pre-computed defaults)
        input_path = DEFAULT_SAMPLE

    # Extract parameters from sliders
    params = {
        'snr_db': float(request.form.get('snr_db', 22)),
        'carrier_freq': int(request.form.get('carrier_freq', 2000)),
        'desync_offsets': [1, 5, int(request.form.get('desync_max', 25))],
        # Use fixed seed (42) only for the pre-computed default sample so results are
        # reproducible and cacheable. Custom uploads get true randomness (seed=None)
        # because real SIGSALY keys were never deterministic.
        'key_seed': 42 if not is_custom_upload else None,
    }

    # If using default sample with default params, serve pre-computed results
    if not is_custom_upload:
        default_results = _load_default_results()
        if default_results:
            default_params = default_results.get('params', {})
            if (default_params.get('snr_db') == params['snr_db'] and
                default_params.get('carrier_freq') == params['carrier_freq'] and
                default_params.get('desync_offsets') == params['desync_offsets']):
                # Params match — serve pre-computed results instantly
                return _render_index(
                    theme=theme,
                    results=default_results,
                    is_default=True,
                    active_source_mode='builtin',
                )

    # Run the pipeline (custom audio or changed params)
    try:
        results = run_web_pipeline(input_path, params)
    except Exception as e:
        return _render_index(
            theme=theme,
            error=f'Pipeline error: {e}',
            active_source_mode=source_mode,
        )
    finally:
        if temp_input_path and os.path.exists(temp_input_path):
            os.unlink(temp_input_path)

    results['source_info']['name'] = source_name

    return _render_index(
        theme=theme,
        results=results,
        active_source_mode=source_mode,
    )


@app.route('/default-sample')
def serve_default_sample():
    """Serve the built-in default sample audio for the preview player."""
    return send_from_directory(
        os.path.dirname(DEFAULT_SAMPLE),
        os.path.basename(DEFAULT_SAMPLE),
        mimetype='audio/mpeg'
    )


@app.route('/session/<session_id>/audio/<filename>')
def serve_audio(session_id, filename):
    """Serve a WAV file from a session directory."""
    if session_id == DEFAULT_SESSION_ID:
        # Serve from pre-computed default output
        if not os.path.isdir(DEFAULT_OUTPUT_DIR):
            return 'Default outputs not found — run scripts/precompute_default.py', 404
        return send_from_directory(DEFAULT_OUTPUT_DIR, filename, mimetype='audio/wav')

    session_dir = os.path.join(tempfile.gettempdir(), f'sigsaly_{session_id}')
    if not os.path.isdir(session_dir):
        return 'Session not found', 404
    return send_from_directory(session_dir, filename, mimetype='audio/wav')


@app.route('/session/<session_id>/spectrogram/<filename>')
def serve_spectrogram(session_id, filename):
    """Serve a spectrogram PNG from a session directory."""
    if session_id == DEFAULT_SESSION_ID:
        if not os.path.isdir(DEFAULT_OUTPUT_DIR):
            return 'Default outputs not found', 404
        return send_from_directory(DEFAULT_OUTPUT_DIR, filename, mimetype='image/png')

    session_dir = os.path.join(tempfile.gettempdir(), f'sigsaly_{session_id}')
    if not os.path.isdir(session_dir):
        return 'Session not found', 404
    return send_from_directory(session_dir, filename, mimetype='image/png')


# ============================================================================
# v3 INTERACTIVE VISUALIZATION ROUTES
# ============================================================================

def _load_v3_defaults():
    """Load pre-computed v3 manifest if available."""
    if not os.path.exists(V3_DEFAULT_MANIFEST):
        return None
    try:
        with open(V3_DEFAULT_MANIFEST, 'r') as f:
            manifest = json.load(f)
        manifest['session_id'] = V3_DEFAULT_SESSION_ID
        return manifest
    except Exception:
        return None


@app.route('/v3')
def v3_interactive():
    """Render the v3 interactive visualization."""
    theme = request.args.get('theme', 'default')
    if theme not in VALID_THEMES:
        theme = 'default'

    manifest = _load_v3_defaults()
    return render_template('v3.html', manifest=manifest, theme=theme)


@app.route('/api/v3/audio/<session_id>/<filename>')
def serve_v3_audio(session_id, filename):
    """Serve a v3 audio variant WAV file."""
    if session_id == V3_DEFAULT_SESSION_ID:
        if not os.path.isdir(V3_DEFAULT_DIR):
            return 'v3 defaults not found — run scripts/precompute_v3.py', 404
        return send_from_directory(V3_DEFAULT_DIR, filename, mimetype='audio/wav')

    session_dir = os.path.join(tempfile.gettempdir(), f'sigsaly_v3_{session_id}')
    if not os.path.isdir(session_dir):
        return 'Session not found', 404
    return send_from_directory(session_dir, filename, mimetype='audio/wav')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='SIGSALY Simulator Web Dashboard')
    parser.add_argument('--port', type=int, default=3001,
                        help='Port to run on (default: 3001)')
    parser.add_argument('--host', default='127.0.0.1',
                        help='Host to bind to (default: 127.0.0.1)')
    parser.add_argument('--debug', action='store_true',
                        help='Enable debug mode')
    args = parser.parse_args()

    has_default = os.path.exists(DEFAULT_RESULTS_JSON)

    print(f"SIGSALY Simulator — Web Dashboard (single-user mode)")
    print(f"  http://{args.host}:{args.port}")
    print(f"  Max audio duration: {MAX_AUDIO_DURATION}s")
    print(f"  Default sample: {DEFAULT_SAMPLE}")
    print(f"  Pre-computed defaults: {'YES — instant load' if has_default else 'NO — run scripts/precompute_default.py'}")
    print()
    print(f"  For multi-user (classroom), use: ./serve.sh")
    print()

    app.run(host=args.host, port=args.port, debug=args.debug)
